#!/usr/bin/env bash
set -euo pipefail

HERE=$(cd "$(dirname "$0")" && pwd)
TOOLCHAIN=${TOOLCHAIN:-/root/toolchains/rocm-llvm23-46fcb339-build}
CLANG23="$TOOLCHAIN/bin/clang++"
ROCM=${ROCM_PATH:-/opt/rocm}
OPUS_INCLUDE_DIR=${OPUS_INCLUDE_DIR:-/root/workspace/aiter/csrc/include}
ARCH=${ARCH:-gfx950}
OUTPUT_TILES_PER_WG=${OUTPUT_TILES_PER_WG:-1}
EXACT_MASK=${EXACT_MASK:-4}
OPAQUE_K_BOUND=${OPAQUE_K_BOUND:-0}
SFB_LDS_CACHE_STAGES=${SFB_LDS_CACHE_STAGES:-0}
SFB_REG_CACHE=${SFB_REG_CACHE:-0}
SFB_PAD_CACHE=${SFB_PAD_CACHE:-0}
C_AGPR=${C_AGPR:-0}
B_SECOND_AGPR=${B_SECOND_AGPR:-0}
B_MAIN_AGPR=${B_MAIN_AGPR:-0}
A_AGPR=${A_AGPR:-0}
DOUBLE_QUEUE=${DOUBLE_QUEUE:-1}
SCALE_PREFETCH_AGPR=${SCALE_PREFETCH_AGPR:-0}
SOURCE_CHANGE=${SOURCE_CHANGE:-2}
SFB_CACHE_DEBUG_STAGE=${SFB_CACHE_DEBUG_STAGE:--1}
SFB_CACHE_REUSE=${SFB_CACHE_REUSE:-1}
SFB_CACHE_SKIP_PRODUCER=${SFB_CACHE_SKIP_PRODUCER:-1}
SFB_CACHE_FULL_GROUPS=${SFB_CACHE_FULL_GROUPS:-0}
BLOCK_ORDER=${BLOCK_ORDER:-0}
OUTPUT_HANDOFF=${OUTPUT_HANDOFF:-1}
PAIR_POSITION=${PAIR_POSITION:-10}
PREFETCH_POSITION=${PREFETCH_POSITION:-1}
LOOP_UNROLL=${LOOP_UNROLL:-4}
PHASE_UNROLL=${PHASE_UNROLL:-0}
CONSUMER_PAIR_CACHE=${CONSUMER_PAIR_CACHE:-0}
GROUP4_PUBLICATION=${GROUP4_PUBLICATION:-0}
LOCAL_REUSE=${LOCAL_REUSE:-0}
PRODUCER_MAP=${PRODUCER_MAP:-0}
SFB_ALIGNED_PAIR=${SFB_ALIGNED_PAIR:-0}
BYTE_SCATTER=${BYTE_SCATTER:-0}
B_PREFETCH_SPLIT=${B_PREFETCH_SPLIT:-4}
B_HEAD_LDS_GROUP=${B_HEAD_LDS_GROUP:-0}
A1_LDS_ORDER=${A1_LDS_ORDER:-0}
A1_WAIT_COUNT=${A1_WAIT_COUNT:-8}
B_PREFETCH_MID_COUNT=${B_PREFETCH_MID_COUNT:-0}
B_PREFETCH_MID_POSITION=${B_PREFETCH_MID_POSITION:-7}
B_PREFETCH_ROLLING=${B_PREFETCH_ROLLING:-0}
B_PREFETCH_ROLLING_FENCE=${B_PREFETCH_ROLLING_FENCE:-0}
PIPELINE_ADVANCE_POSITION=${PIPELINE_ADVANCE_POSITION:-10}
B_BALANCED_PRODUCER=${B_BALANCED_PRODUCER:-0}
DEFER_QUEUE_COPY=${DEFER_QUEUE_COPY:-0}
QUEUE_FENCE=${QUEUE_FENCE:-0}
QUEUE8=${QUEUE8:-0}
PAIRED_REFILL=${PAIRED_REFILL:-0}
BUILD_SUFFIX=
if (( OPAQUE_K_BOUND != 0 )); then
    BUILD_SUFFIX+="_okb"
fi
if (( SFB_LDS_CACHE_STAGES != 0 )); then
    BUILD_SUFFIX+="_sfblds${SFB_LDS_CACHE_STAGES}"
fi
if (( SFB_REG_CACHE != 0 )); then
    BUILD_SUFFIX+="_sfbreg${SFB_REG_CACHE}"
fi
if (( SFB_PAD_CACHE != 0 )); then
    BUILD_SUFFIX+="_sfbpad${SFB_PAD_CACHE}"
fi
if (( C_AGPR != 0 )); then
    BUILD_SUFFIX+="_cagpr"
fi
if (( B_SECOND_AGPR != 0 )); then
    BUILD_SUFFIX+="_b2agpr"
fi
if (( B_MAIN_AGPR != 0 )); then
    BUILD_SUFFIX+="_b0agpr"
fi
if (( A_AGPR != 0 )); then
    BUILD_SUFFIX+="_aagpr"
fi
if (( DOUBLE_QUEUE == 0 )); then
    BUILD_SUFFIX+="_sq"
fi
if (( SCALE_PREFETCH_AGPR != 0 )); then
    BUILD_SUFFIX+="_pfagpr"
fi
if (( SOURCE_CHANGE != 2 )); then
    BUILD_SUFFIX+="_src${SOURCE_CHANGE}"
fi
if (( BLOCK_ORDER != 0 )); then
    BUILD_SUFFIX+="_bo${BLOCK_ORDER}"
fi
if (( OUTPUT_HANDOFF == 0 )); then
    BUILD_SUFFIX+="_nohandoff"
fi
if (( PAIR_POSITION != 10 )); then
    BUILD_SUFFIX+="_pair${PAIR_POSITION}"
fi
if (( PREFETCH_POSITION != 1 )); then
    BUILD_SUFFIX+="_pf${PREFETCH_POSITION}"
fi
if (( LOOP_UNROLL != 4 )); then
    BUILD_SUFFIX+="_u${LOOP_UNROLL}"
fi
if (( PHASE_UNROLL != 0 )); then
    BUILD_SUFFIX+="_phase"
fi
if (( CONSUMER_PAIR_CACHE != 0 )); then
    BUILD_SUFFIX+="_paircache${CONSUMER_PAIR_CACHE}"
fi
if (( GROUP4_PUBLICATION != 0 )); then
    BUILD_SUFFIX+="_group4"
fi
if (( LOCAL_REUSE != 0 )); then
    BUILD_SUFFIX+="_reuse${LOCAL_REUSE}"
fi
if (( PRODUCER_MAP != 0 )); then
    BUILD_SUFFIX+="_pmap${PRODUCER_MAP}"
fi
if (( SFB_ALIGNED_PAIR != 0 )); then
    BUILD_SUFFIX+="_sfb64"
fi
if (( BYTE_SCATTER != 0 )); then
    BUILD_SUFFIX+="_scatter"
fi
if (( B_PREFETCH_SPLIT != 4 )); then
    BUILD_SUFFIX+="_bs${B_PREFETCH_SPLIT}"
fi
if (( B_HEAD_LDS_GROUP != 0 )); then
    BUILD_SUFFIX+="_bhg${B_HEAD_LDS_GROUP}"
fi
if (( A1_LDS_ORDER != 0 )); then
    BUILD_SUFFIX+="_a1o${A1_LDS_ORDER}"
fi
if (( A1_WAIT_COUNT != 8 )); then
    BUILD_SUFFIX+="_a1w${A1_WAIT_COUNT}"
fi
if (( B_PREFETCH_ROLLING != 0 )); then
    BUILD_SUFFIX+="_broll${B_PREFETCH_ROLLING}"
fi
if (( B_PREFETCH_ROLLING_FENCE != 0 )); then
    BUILD_SUFFIX+="_brollf"
fi
if (( B_PREFETCH_MID_COUNT != 0 )); then
    BUILD_SUFFIX+="_bm${B_PREFETCH_MID_COUNT}p${B_PREFETCH_MID_POSITION}"
fi
if (( PIPELINE_ADVANCE_POSITION != 10 )); then
    BUILD_SUFFIX+="_adv${PIPELINE_ADVANCE_POSITION}"
fi
if (( B_BALANCED_PRODUCER != 0 )); then
    BUILD_SUFFIX+="_bbal"
fi
if (( DEFER_QUEUE_COPY != 0 )); then
    BUILD_SUFFIX+="_defercopy"
fi
if (( QUEUE_FENCE != 0 )); then
    BUILD_SUFFIX+="_qf${QUEUE_FENCE}"
fi
if (( QUEUE8 != 0 )); then
    BUILD_SUFFIX+="_q8"
fi
if (( PAIRED_REFILL != 0 )); then
    BUILD_SUFFIX+="_pairedrefill"
fi
BUILD_DIR=${BUILD_DIR:-$HERE/build_t${OUTPUT_TILES_PER_WG}_exact${EXACT_MASK}${BUILD_SUFFIX}}

FLAGS=(
    -I"$HERE" -I"$OPUS_INCLUDE_DIR"
    -std=c++17 -O3 -ffast-math
    --offload-arch="$ARCH" --rocm-path="$ROCM"
)
LDFLAGS=(
    -fopenmp -L"$ROCM/lib/llvm/lib" -lomp
    -Wl,-rpath,"$ROCM/lib/llvm/lib"
    -L"$ROCM/lib" -lamdhip64 -Wl,-rpath,"$ROCM/lib"
)

(( (OUTPUT_TILES_PER_WG >= 1 && OUTPUT_TILES_PER_WG <= 4) || OUTPUT_TILES_PER_WG == 8 ))
[[ "$OPAQUE_K_BOUND" == 0 || "$OPAQUE_K_BOUND" == 1 ]]
(( SFB_LDS_CACHE_STAGES >= 0 && SFB_LDS_CACHE_STAGES <= 20 &&
   SFB_LDS_CACHE_STAGES % 4 == 0 ))
(( SFB_REG_CACHE >= 0 && SFB_REG_CACHE <= 2 ))
[[ "$SFB_PAD_CACHE" == 0 || "$SFB_PAD_CACHE" == 1 ]]
if (( SFB_LDS_CACHE_STAGES != 0 )); then
    [[ "$OUTPUT_TILES_PER_WG" == 2 ]]
fi
[[ "$C_AGPR" == 0 || "$C_AGPR" == 1 ]]
[[ "$B_SECOND_AGPR" == 0 || "$B_SECOND_AGPR" == 1 ]]
[[ "$B_MAIN_AGPR" == 0 || "$B_MAIN_AGPR" == 1 ]]
[[ "$A_AGPR" == 0 || "$A_AGPR" == 1 ]]
[[ "$DOUBLE_QUEUE" == 0 || "$DOUBLE_QUEUE" == 1 ]]
[[ "$SCALE_PREFETCH_AGPR" == 0 || "$SCALE_PREFETCH_AGPR" == 1 ]]
(( SOURCE_CHANGE >= 0 && SOURCE_CHANGE <= 4 ))
[[ "$BLOCK_ORDER" == 0 || "$BLOCK_ORDER" == 6 ||
   "$BLOCK_ORDER" == 7 || "$BLOCK_ORDER" == 8 ||
   "$BLOCK_ORDER" == 9 || "$BLOCK_ORDER" == 10 ||
   "$BLOCK_ORDER" == 11 || "$BLOCK_ORDER" == 12 ]]
if (( OUTPUT_TILES_PER_WG == 8 )); then
    [[ "$BLOCK_ORDER" != 8 && "$BLOCK_ORDER" != 11 ]]
fi
[[ "$OUTPUT_HANDOFF" == 0 || "$OUTPUT_HANDOFF" == 1 ]]
[[ "$PAIR_POSITION" == 0 || "$PAIR_POSITION" == 1 ||
   "$PAIR_POSITION" == 2 || "$PAIR_POSITION" == 3 ||
   "$PAIR_POSITION" == 4 || "$PAIR_POSITION" == 8 ||
   "$PAIR_POSITION" == 9 || "$PAIR_POSITION" == 10 ]]
[[ "$PREFETCH_POSITION" == 0 || "$PREFETCH_POSITION" == 1 ||
   "$PREFETCH_POSITION" == 2 || "$PREFETCH_POSITION" == 3 ||
   "$PREFETCH_POSITION" == 4 || "$PREFETCH_POSITION" == 8 ||
   "$PREFETCH_POSITION" == 25 || "$PREFETCH_POSITION" == 35 ]]
[[ "$LOOP_UNROLL" == 1 || "$LOOP_UNROLL" == 2 ||
   "$LOOP_UNROLL" == 4 || "$LOOP_UNROLL" == 8 ||
   "$LOOP_UNROLL" == 16 ]]
[[ "$PHASE_UNROLL" == 0 || "$PHASE_UNROLL" == 1 ]]
(( CONSUMER_PAIR_CACHE >= 0 && CONSUMER_PAIR_CACHE <= 5 ))
[[ "$GROUP4_PUBLICATION" == 0 || "$GROUP4_PUBLICATION" == 1 ]]
(( LOCAL_REUSE >= 0 && LOCAL_REUSE <= 6 ))
(( PRODUCER_MAP >= 0 && PRODUCER_MAP <= 6 ))
[[ "$SFB_ALIGNED_PAIR" == 0 || "$SFB_ALIGNED_PAIR" == 1 ]]
[[ "$BYTE_SCATTER" == 0 || "$BYTE_SCATTER" == 1 ]]
(( B_PREFETCH_SPLIT >= 0 && B_PREFETCH_SPLIT <= 8 ))
[[ "$B_HEAD_LDS_GROUP" == 0 || "$B_HEAD_LDS_GROUP" == 2 ||
   "$B_HEAD_LDS_GROUP" == 4 || "$B_HEAD_LDS_GROUP" == 8 ]]
(( A1_LDS_ORDER >= 0 && A1_LDS_ORDER <= 3 ))
[[ "$A1_WAIT_COUNT" == 6 || "$A1_WAIT_COUNT" == 8 ]]
(( B_PREFETCH_ROLLING >= 0 && B_PREFETCH_ROLLING <= 3 ))
[[ "$B_PREFETCH_ROLLING_FENCE" == 0 || "$B_PREFETCH_ROLLING_FENCE" == 1 ]]
if (( B_PREFETCH_ROLLING )); then
    [[ "$B_PREFETCH_SPLIT" == 2 && "$B_PREFETCH_MID_COUNT" == 0 ]]
fi
(( B_PREFETCH_MID_COUNT >= 0 && B_PREFETCH_MID_COUNT + B_PREFETCH_SPLIT <= 8 ))
[[ "$B_PREFETCH_MID_POSITION" == 6 || "$B_PREFETCH_MID_POSITION" == 7 ]]
[[ "$PIPELINE_ADVANCE_POSITION" == 8 || "$PIPELINE_ADVANCE_POSITION" == 9 ||
   "$PIPELINE_ADVANCE_POSITION" == 10 || "$PIPELINE_ADVANCE_POSITION" == 11 ||
   "$PIPELINE_ADVANCE_POSITION" == 12 || "$PIPELINE_ADVANCE_POSITION" == 14 ||
   "$PIPELINE_ADVANCE_POSITION" == 16 ]]
[[ "$DEFER_QUEUE_COPY" == 0 || "$DEFER_QUEUE_COPY" == 1 ]]
[[ "$B_BALANCED_PRODUCER" == 0 || "$B_BALANCED_PRODUCER" == 1 ]]
(( QUEUE_FENCE >= 0 && QUEUE_FENCE <= 2 ))
[[ "$QUEUE8" == 0 || "$QUEUE8" == 1 ]]
[[ "$PAIRED_REFILL" == 0 || "$PAIRED_REFILL" == 1 ]]
if (( PAIRED_REFILL )); then
    [[ "$DOUBLE_QUEUE" == 1 && "$QUEUE8" == 0 ]]
fi
if (( QUEUE8 )); then
    [[ "$DOUBLE_QUEUE" == 0 ]]
fi
if [[ -e "$BUILD_DIR/kernel.exe" ]]; then
    echo "refusing to overwrite existing image: $BUILD_DIR/kernel.exe" >&2
    exit 1
fi
mkdir -p "$BUILD_DIR"

"$CLANG23" -x hip "$HERE/host.cc" "${FLAGS[@]}" \
    -DMXFP8_SCALE_OUTPUT_TILES_PER_WG="$OUTPUT_TILES_PER_WG" \
    -fopenmp -I"$ROCM/lib/llvm/include" \
    -c -o "$BUILD_DIR/host.o"

DEVICE_DEFINES=(
    -D__HIPCC_RTC__
    -DMXFP8_LOCAL_OUTPUT_TILES_PER_WG="$OUTPUT_TILES_PER_WG"
    -DMXFP8_ISOLATED_SOURCE_CHANGE="$SOURCE_CHANGE"
    -DMXFP8_ROW_SCALE_PRODUCER_MODE=1
    -DMXFP8_ROW_SCALE_PAIR_POSITION="$PAIR_POSITION"
    -DMXFP8_ROW_SCALE_PREFETCH_POSITION="$PREFETCH_POSITION"
    -DMXFP8_ROW_SCALE_LOOP_UNROLL="$LOOP_UNROLL"
    -DMXFP8_ROW_SCALE_PHASE_UNROLL="$PHASE_UNROLL"
    -DMXFP8_ROW_SCALE_CONSUMER_PAIR_CACHE="$CONSUMER_PAIR_CACHE"
    -DMXFP8_ROW_SCALE_GROUP4_PUBLICATION="$GROUP4_PUBLICATION"
    -DMXFP8_ROW_SCALE_LOCAL_REUSE="$LOCAL_REUSE"
    -DMXFP8_ROW_SCALE_PRODUCER_MAP="$PRODUCER_MAP"
    -DMXFP8_ROW_SCALE_SFB_ALIGNED_PAIR="$SFB_ALIGNED_PAIR"
    -DMXFP8_ROW_SCALE_BYTE_SCATTER="$BYTE_SCATTER"
    -DMXFP8_B_PREFETCH_SPLIT="$B_PREFETCH_SPLIT"
    -DMXFP8_B_HEAD_LDS_GROUP="$B_HEAD_LDS_GROUP"
    -DMXFP8_A1_LDS_ORDER="$A1_LDS_ORDER"
    -DMXFP8_A1_WAIT_COUNT="$A1_WAIT_COUNT"
    -DMXFP8_B_PREFETCH_MID_COUNT="$B_PREFETCH_MID_COUNT"
    -DMXFP8_B_PREFETCH_MID_POSITION="$B_PREFETCH_MID_POSITION"
    -DMXFP8_B_PREFETCH_ROLLING="$B_PREFETCH_ROLLING"
    -DMXFP8_B_PREFETCH_ROLLING_FENCE="$B_PREFETCH_ROLLING_FENCE"
    -DMXFP8_PIPELINE_ADVANCE_POSITION="$PIPELINE_ADVANCE_POSITION"
    -DMXFP8_B_BALANCED_PRODUCER="$B_BALANCED_PRODUCER"
    -DMXFP8_ROW_SCALE_DEFER_QUEUE_COPY="$DEFER_QUEUE_COPY"
    -DMXFP8_ROW_SCALE_QUEUE_FENCE="$QUEUE_FENCE"
    -DMXFP8_ROW_SCALE_QUEUE8="$QUEUE8"
    -DMXFP8_ROW_SCALE_PAIRED_REFILL="$PAIRED_REFILL"
    -DMXFP8_ROW_SCALE_DOUBLE_QUEUE="$DOUBLE_QUEUE"
    -DMXFP8_ROW_SCALE_SFB_LDS_CACHE_STAGES="$SFB_LDS_CACHE_STAGES"
    -DMXFP8_ROW_SCALE_SFB_REG_CACHE="$SFB_REG_CACHE"
    -DMXFP8_ROW_SCALE_SFB_PAD_CACHE="$SFB_PAD_CACHE"
    -DMXFP8_ROW_C_AGPR="$C_AGPR"
    -DMXFP8_ROW_B_SECOND_AGPR="$B_SECOND_AGPR"
    -DMXFP8_ROW_B_MAIN_AGPR="$B_MAIN_AGPR"
    -DMXFP8_ROW_A_AGPR="$A_AGPR"
    -DMXFP8_ROW_SCALE_SFB_CACHE_DEBUG_STAGE="$SFB_CACHE_DEBUG_STAGE"
    -DMXFP8_ROW_SCALE_SFB_CACHE_REUSE="$SFB_CACHE_REUSE"
    -DMXFP8_ROW_SCALE_SFB_CACHE_SKIP_PRODUCER="$SFB_CACHE_SKIP_PRODUCER"
    -DMXFP8_ROW_SCALE_SFB_CACHE_FULL_GROUPS="$SFB_CACHE_FULL_GROUPS"
    -DMXFP8_BLOCK_ORDER_EXPERIMENT="$BLOCK_ORDER"
    -DMXFP8_LOCAL_OUTPUT_HANDOFF="$OUTPUT_HANDOFF"
    -DMXFP8_ROW_SCALE_PREFETCH_AGPR="$SCALE_PREFETCH_AGPR"
    -DMXFP8_EXACT_8192="$EXACT_MASK"
    -DMXFP8_OPAQUE_K_BOUND="$OPAQUE_K_BOUND"
)
declare -p TOOLCHAIN ARCH OUTPUT_TILES_PER_WG EXACT_MASK OPAQUE_K_BOUND SOURCE_CHANGE \
    OUTPUT_HANDOFF PAIR_POSITION PREFETCH_POSITION LOOP_UNROLL PHASE_UNROLL \
    DOUBLE_QUEUE QUEUE8 PAIRED_REFILL QUEUE_FENCE DEFER_QUEUE_COPY B_PREFETCH_SPLIT B_HEAD_LDS_GROUP \
    A1_LDS_ORDER A1_WAIT_COUNT B_PREFETCH_ROLLING B_PREFETCH_ROLLING_FENCE \
    B_PREFETCH_MID_COUNT B_PREFETCH_MID_POSITION PIPELINE_ADVANCE_POSITION B_BALANCED_PRODUCER \
    SFB_ALIGNED_PAIR BYTE_SCATTER DEVICE_DEFINES > "$BUILD_DIR/config.sh"
sha256sum "$HERE/kernel.cc" "$HERE/host.cc" \
    "$HERE/gemm_a8w8_mxfp8_scale_kernel.hpp" \
    "$HERE/gemm_a8w8_mxfp8_scale_common.h" > "$BUILD_DIR/source.sha256"
"$CLANG23" -x hip "$HERE/kernel.cc" "${FLAGS[@]}" \
    "${DEVICE_DEFINES[@]}" -c -o "$BUILD_DIR/kernel.o"
"$CLANG23" "$BUILD_DIR/kernel.o" "$BUILD_DIR/host.o" \
    --offload-arch="$ARCH" --rocm-path="$ROCM" "${LDFLAGS[@]}" \
    -o "$BUILD_DIR/kernel.exe"

"$TOOLCHAIN/bin/llvm-objcopy" \
    --dump-section=.hip_fatbin="$BUILD_DIR/kernel.fb" \
    "$BUILD_DIR/kernel.exe"
"$TOOLCHAIN/bin/clang-offload-bundler" -type=o \
    -targets="hipv4-amdgcn-amd-amdhsa--$ARCH" \
    -input="$BUILD_DIR/kernel.fb" -output="$BUILD_DIR/kernel.dev" -unbundle
"$TOOLCHAIN/bin/llvm-objdump" -d --mcpu="$ARCH" \
    "$BUILD_DIR/kernel.dev" > "$BUILD_DIR/kernel.isa"
"$TOOLCHAIN/bin/llvm-readelf" --notes "$BUILD_DIR/kernel.dev" \
    > "$BUILD_DIR/kernel.notes"
"$CLANG23" -x hip "$HERE/kernel.cc" "${FLAGS[@]}" \
    "${DEVICE_DEFINES[@]}" --cuda-device-only -S \
    -o "$BUILD_DIR/kernel.s"

echo "built $BUILD_DIR/kernel.exe (output_tiles_per_wg=$OUTPUT_TILES_PER_WG exact_mask=$EXACT_MASK sfb_lds_cache_stages=$SFB_LDS_CACHE_STAGES sfb_reg_cache=$SFB_REG_CACHE sfb_pad_cache=$SFB_PAD_CACHE source_change=$SOURCE_CHANGE block_order=$BLOCK_ORDER output_handoff=$OUTPUT_HANDOFF pair_position=$PAIR_POSITION prefetch_position=$PREFETCH_POSITION loop_unroll=$LOOP_UNROLL consumer_pair_cache=$CONSUMER_PAIR_CACHE group4_publication=$GROUP4_PUBLICATION local_reuse=$LOCAL_REUSE producer_map=$PRODUCER_MAP c_agpr=$C_AGPR a_agpr=$A_AGPR b_main_agpr=$B_MAIN_AGPR b_second_agpr=$B_SECOND_AGPR double_queue=$DOUBLE_QUEUE scale_prefetch_agpr=$SCALE_PREFETCH_AGPR sfb_aligned_pair=$SFB_ALIGNED_PAIR byte_scatter=$BYTE_SCATTER b_prefetch_split=$B_PREFETCH_SPLIT defer_queue_copy=$DEFER_QUEUE_COPY queue_fence=$QUEUE_FENCE queue8=$QUEUE8)"
